services:
  - type: web
    name: fedex-backend
    env: docker
    dockerfilePath: ./FEDEX/backend/Dockerfile
    dockerContext: ./FEDEX/backend
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000

